### ISSUE TITLE
Tang Nano 9k support?

### ISSUE THREAD

**Issue by chenzhuoyu** [YosysHQ/apicula#105]
Is there any plans to support the Tang Nano 9k board?

**Comment by chenzhuoyu** [comment]
@pepijndevos That's nice. But it does not listed in the README.md, so it probably needs to be updated?

**Comment by pepijndevos** [comment]
Correct. Hmmm if you have the thing sitting on your desk feel free to add it to the list with the correct part number, else I'll do it myself later.

**Comment by chenzhuoyu** [comment]
@pepijndevos I don't own a Tang Nano 9k at this moment, but I'm considering buying one. Once it arrives I'll give it a try.

**Comment by fanoush** [comment]
Hi, just received this board today :-) This is what openFPGAloader shows with tang nano 9k
```
openFPGALoader.exe --detect
←[94mJtag frequency : requested 6.00MHz    -> real 6.00MHz   ←[0m
index 0:
        idcode 0x100481b
        manufacturer Gowin
        family GW1N
        model  GW1N(R)-9C
        irlength 8
```
and here is the chip
![9k-1280](https://user-images.githubusercontent.com/785488/170726905-9a1b2f84-3087-4e86-9a88-4b17055817ae.jpg)
hope it helps

**Comment by pepijndevos** [comment]
oh yea forgot about this, thanks! saves me a trip upstairs to fetch my board, added : https://github.com/YosysHQ/apicula/commit/4b62db6848037dffc3569cc1fc5a47c463e54a94

**Comment by pepijndevos** [comment]
Needs an extra family flag though, because the C is not in the device number: https://github.com/YosysHQ/apicula/blob/4b62db6848037dffc3569cc1fc5a47c463e54a94/examples/Makefile#L79

Should find a way to work that into the readme
