### ISSUE TITLE
Add supported features matrix

### ISSUE THREAD

**Issue by uis246** [YosysHQ/apicula#106]
For each model. Like [this](https://nouveau.freedesktop.org/FeatureMatrix.html).

**Comment by pepijndevos** [comment]
There is https://github.com/YosysHQ/yosys/wiki/FPGA-family-feature-matrix/ and there is no difference per model. Supported models are listed in the readme. Although I've just been informed that Tang Nano 9k is missing, which I'll fix.

**Comment by uis246** [comment]
Hard core

**Comment by uis246** [comment]
I mean Cortex-M hard core not listed there
