### ISSUE TITLE
Difference between Apycula and Apicula???

### ISSUE THREAD

**Issue by Harvie** [YosysHQ/apicula#120]
What is difference between Apycula and Apicula?
Just taking a first look at this project and it is rather confusing. Can you please explain this in README?

I guess aPYcula is pun indicating that tools are made for python. But are there some other non-python components of apicula that i have to install separately in adition to `doing pip install apycula`?

**Comment by pepijndevos** [comment]
Yea that's all there is to it. The project is called Apicula, which means little bee in Latin. The Python package is called Apycula for obvious reasons. It doesn't really matter, it's just a name, you can use the project without ever thinking about the name of the project.

**Comment by Harvie** [comment]
so `pip install apycula` is enough to get all the components?

**Comment by pepijndevos** [comment]
yes, just as it says in the readme
