### ISSUE TITLE
Incorrect chipdb version ?

### ISSUE THREAD

**Issue by meyanik** [YosysHQ/apicula#136]
I'm a newbie to the project. I have a Tang-nano1k board and trying to flash a basic led=button project. But when I am using makefile which i wrote using example makefile i got this error:
" ERROR: Incorrect chipdb version 1 is used. Version 2 is required "
I think device name should be different. I am using GW1NZ-LV1QN48C6/I5
my makefile line:
" $(NEXTPNR) --json $< --write $@ --family GW1NZ-1 --cst tangnano1k.cst --device GW1NZ-LV1QN48C6/I5 "
any ideas how can i fix it ?

**Comment by pepijndevos** [comment]
Update apycula to 0.5.1

**Comment by meyanik** [comment]
After installing Apycula-0.5.1 over pip, i get the same error unfortunately :(

**Comment by yrabbit** [comment]
I don't know much about installations, but let's try to work it out:
- This error is printed by nextpnr;
- The bases, which are not external files, are embedded in nextpnr during the compilation process;

You probably have a creepy version of nextpnr which has the master branch code, but the bases were used from an older version of apicula when building it.

If you compiled nextpnr yourself, the sequence may help:
install the latest apicula -> compile nextpnr -> compile example

in theory:)

**Comment by mmicko** [comment]
@meyanik other option is to use prebuilt oss-cad-suite from  https://github.com/YosysHQ/oss-cad-suite-build/releases/latest

**Comment by meyanik** [comment]
Thank you all, after removing and re-installing apycula with pip and pre-compiling nextpnr  bba.cmake files and installing nextpnr, i got it worked.
