### ISSUE TITLE
TangNano 9k clocking from external source working only in some configurations at random

### ISSUE THREAD

**Issue by wingrime** [YosysHQ/apicula#145]
blinky.v don't work (tested on 2 boards), but blinky-osc.v works fine. 

After adding --enable-gobals works again, but after some unrelated changes in v file broken again 
(after rebuild & reflash)

**Comment by yrabbit** [comment]
Can you specify at which --seed you steadily get a non-functioning image? 
This makes it easier to deal with random bugs:)

**Comment by yrabbit** [comment]
Can you please check with the latest nextpnr and apicula?

**Comment by wingrime** [comment]
ок, when some time

**Comment by yrabbit** [comment]
Should work after https://github.com/YosysHQ/apicula/pull/199
