### ISSUE TITLE
gowin_pack fails on nano9k with strange LVCMOS18 error

### ISSUE THREAD

**Issue by martell** [YosysHQ/apicula#158]
I've been trying to build my_hdmi_device by splinedrive with apicula and have gotten pretty far along with some tweaks.
gowin_pack with the current apicula/chipdb fails with this strange error on the nano9k

```
gowin_pack -d GW1N-9C -o chip_balls.fs chip_balls_pnr.json
Traceback (most recent call last):
  File "/opt/homebrew/bin/gowin_pack", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/apycula/gowin_pack.py", line 703, in main
    place(db, tilemap, bels, cst, args)
  File "/opt/homebrew/lib/python3.10/site-packages/apycula/gowin_pack.py", line 452, in place
    raise Exception(f"Different I/O modes for the same bank {bank} were specified: {iostd} and {flag_name_val[1]}")
Exception: Different I/O modes for the same bank 1 were specified: LVCMOS18 and LVCMOS33
make: *** [chip_balls.fs] Error 1
```

Steps to reproduce

```
git clone https://github.com/martell/my_hdmi_device
cd my_hdmi_device
git checkout yosys-nano9k
make -f Makefile.nano9k
```

@yrabbit @pepijndevos This seems very close since merging #156

**Comment by yrabbit** [comment]
Let's see if it doesn't get resolved after we beat 

https://github.com/YosysHQ/apicula/issues/157

**Comment by martell** [comment]
Continuing from there trying to use LVDS here this is where we get stuck

I thought the nano9k had emulated lvds instead of true from reading docs and this reddit thread proved useful.
https://www.reddit.com/r/GowinFPGA/comments/wu96b5/difference_between_gowin_true_and_emulated_lvds/

Using ELVDS_OBUF I get the following error - I presume apicula just doesn't have support for it yet ?
```
7.3.21. Executing AST frontend in derive mode using pre-parsed AST for module `\ball'.
Generating RTLIL representation for module `$paramod$df58ad4b67c0055eee254f8d5891cca82e58fb35\ball'.
ERROR: Module `\ELVDS_OBUF' referenced in module `\chip_balls' in cell `\clk_tlvds_obuf' is not part of the design.
```

Using TLVDS gowin pack errors out with this
```
Exception: IOT42A. TLVDS_OBUF is not allowed for a given io standard LVCMOS33
```

I presume some logic has to be added to apicula for ELVDS_OBUF which should work with LVCMOS33 ?
I'd love to look at implementing this if you can point me in the right direction (assuming it is not too complicated)

**Comment by yrabbit** [comment]
Oh shit, I totally forgot about this feature of the Tangnano9k board - there are TLVDS pins, but they are not outputted to the HDMI connector. Instead, the LVDS emulation is put there.
And we don't support this primitive yet if I'm not mistaken :(

**Comment by yrabbit** [comment]
I don't think changing the standard will help: TLVDS primitives are hardwired to their respective pins and cannot be placed on the HDMI pins on that particular board.

**Comment by yrabbit** [comment]
I don't know your qualifications and can't judge whether it's difficult or not:
- To add the recognition of the ELVDS primitive proper to yosys;
- add the creation of such Bels in apycula bases;
- teach nextpnr how to properly place and route such things;
- add to apycula bases what bits should be set for given ELVDS parameters.

To me, this is a pain in the ass.
But I will do it after PLL anyway.

**Comment by yrabbit** [comment]
The vendor tools on your 4k project also show good use of LUT and DFF :)
Here we are clearly losing out on optimization.
![dff](https://user-images.githubusercontent.com/6075465/215386640-690f9f74-7ef3-416d-b3f9-1f8e2e71cd2e.png)

**Comment by yrabbit** [comment]
ELVDS family primitives added by https://github.com/YosysHQ/apicula/pull/177
