### ISSUE TITLE
OSCH seems broken

### ISSUE THREAD

**Issue by whitequark** [YosysHQ/apicula#193]
This design doesn't output anything:
```
module top(output clkout);
  OSCH #(.FREQ_DIV(32'd100)) osc (.OSCOUT(clkout));
endmodule
```

Full archive, for testing on Tang Nano: 
[broken.zip](https://github.com/YosysHQ/apicula/files/12290726/broken.zip)

This is with:

```
"yowasp-nextpnr-gowin" -- Next Generation Place and Route (Version nextpnr-0.6)
```

**Comment by whitequark** [comment]
Confirmed that it works fine with the Gowin toolchain.

**Comment by yrabbit** [comment]
Have you tried getting gowin_pack.py from master?

**Comment by whitequark** [comment]
Fixed in master.
