### ISSUE TITLE
szfpga board support

### ISSUE THREAD

**Issue by tpimh** [YosysHQ/apicula#216]
@yrabbit added support for a szfpga board in the commit d350cb7cee68144fdef159e8104bb7652ed91fdc. However, it is not mentioned anywhere in the documentation. Should the documentation be updated to add mention of this specific board?

The board has GW1NR-LV9LQ144PC6/I5, so I suppose it's [this product](https://www.szfpga.com/mod_product-view-p_id-114.html).

**Comment by yrabbit** [comment]
Well, yes, this is the board. But I just don’t think that anyone except me has it, and I added it so that I wouldn’t have to apply a patch with its support every time.
![szfpga](https://github.com/YosysHQ/apicula/assets/6075465/fa293102-e913-4883-8a58-3a60d0a5a94c)

**Comment by tpimh** [comment]
Would it be okay to just add a mention of this board support to readme?
