### ISSUE TITLE
Rewrite the documentation on the file formats used in Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [YosysHQ/apicula#23]

**Comment by pepijndevos** [comment]
Please motivate. I have no idea what Kaitai structs are and why it would be worth the time to rewrite a bunch of things.

**Comment by KOLANICH** [comment]
Just a formal language for describing formats. You specify a format in YAML in a declarative way, the compiler generates a parser for you. Python is supported as a target language.

**Comment by pepijndevos** [comment]
Happy to take a PR that rewrites the current parsers in Kaitai, but since the current ones already work fine, it's not a priority for me to spend my time on it.
