### ISSUE TITLE
Are BRAMs supported?

### ISSUE THREAD

**Issue by stacksmith** [YosysHQ/apicula#267]
Having trouble inferring BRAMS on a tang nano9K...

I seem to remember reading elsewhere that BRAMS were not supported yet, but it was a while ago.

**Comment by yrabbit** [comment]
Do you have a broken example and a compilation log?

You can look into the directory https://github.com/YosysHQ/apicula/tree/master/examples/himbaechel - there is not only direct use of memory primitives (SP, SDP, DP.. etc) but also inferring as part of the RISCV emulator, which works fine on Tangnano9k - https://github.com/YosysHQ/apicula/blob/master/examples/himbaechel/femto-riscv-18.v

**Comment by stacksmith** [comment]
Thank you, I was hoping to hear that it works.  I didn't have working code until today, just got a 65c02 core up with a 2K rom and a 2K RAM using the awful gowin toolchain (takes just over a minute to build!).  Tomorrow will rebuild with apicula.  Hoping for a faster turnaround, as a minute is way too slow.

Thanks again

**Comment by stacksmith** [comment]
OK, seems to work fine.  Thank you.
