### ISSUE TITLE
Gowin - tang nano 4K, 9K Yosys generated bitstreams cannot be programmed with Gowin EDA

### ISSUE THREAD

**Issue by fedor-goncharov** [YosysHQ/apicula#271]
I have two Gowin tang nano boards 4K and 9K and I generate bitstream via OSS-CAD suite. 

Sometimes there are problems to flash .fs files to board via openFPGALoader, so I would like to use 
native Gowin EDA - Programmer which seem to be quite stable. 

However, when I choose .fs file generated by Yosys, Gowin tells me that the board id-code is not good : 

For example for 9K : 

in Gowind EDA it is 1100481B
in your make id-code it is 1100481b 

i.e., difference in 'B' vs 'b' (maybe it is simply shitty python style of EDA). Do you know this issue?

In other direction, could you tell me where in the OSS cad suite source code I could change 'b' -> to 'B' to allow myself to use 
Gowin programmer?

**Comment by yrabbit** [comment]
Two points:

 - ID in the .FS file is stored as a number, and not as a string, you yourself can easily find it at the very beginning of the file - the line begins with the number 6 (8 bit format, MSB first), then all the ID bytes follow:
 
```
0000011000000000000000000000000000010001000000000100100000011011
       6                           1   1   0   0   4   8   1   b
```

  -  We do not construct/rewrite the ID anywhere - when creating the database of Apicula chips, it once launches Gowin IDE with an almost empty module and remember the entire generated Gowin Ide bitstream as a template.
